#!/bin/bash -l
# This script was generated by ulhpc-submit
# Generated at: 2026-06-19T16:55:36

#SBATCH --job-name=vibe-hpc-smoke
#SBATCH --partition=batch
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=00:30:00
#SBATCH --output=job_%j.out
#SBATCH --error=job_%j.err
#SBATCH --chdir=/home/users/twang/hpc_runs/vibe-coding-planning

set -uo pipefail
echo "[ulhpc-submit] job started at $(date)"
echo "[ulhpc-submit] running on host: $(hostname)"
echo "[ulhpc-submit] remote dir: /home/users/twang/hpc_runs/vibe-coding-planning"

echo "[ulhpc-submit] configuring environment on compute node"
if module load miniconda3 2>/dev/null && command -v conda >/dev/null 2>&1; then
    echo "[ulhpc-submit] using conda environment"
    set +u  # avoid conda uninitialized-variable errors
    source "$(conda info --base)/etc/profile.d/conda.sh"
    set -u
    if ! conda env list | grep -qE "^\s*mini-swe\s+"; then
        conda create -n mini-swe python=3.11 -y
    else
        conda run -n mini-swe pip install -r requirements.txt
    fi
    conda activate mini-swe
    pip install -r requirements.txt
else
    echo "[ulhpc-submit] WARNING: conda not available; falling back to pip. Some packages may differ from the conda environment."
    module load lang/Python/3.11
    python -m pip install --user -r requirements.txt
fi
echo "[ulhpc-submit] environment ready"

echo "[ulhpc-submit] executing user command"
set +e
bash -lc 'set -euo pipefail
echo "[vibe-hpc-smoke] started at $(date)"
echo "[vibe-hpc-smoke] host=$(hostname)"
echo "[vibe-hpc-smoke] pwd=$(pwd)"
if command -v module >/dev/null 2>&1; then
  module load miniconda3 2>/dev/null || true
fi
if command -v conda >/dev/null 2>&1; then
  set +u
  source "$(conda info --base)/etc/profile.d/conda.sh"
  set -u
  conda activate "mini-swe"
fi
EASYBUILD_PYTHON="/opt/apps/easybuild/systems/iris/rhel810-20250803/2023b/broadwell/software/Python/3.11.5-GCCcore-13.2.0/bin/python"
if [[ -x "$EASYBUILD_PYTHON" ]]; then
  PYTHON_BIN="$EASYBUILD_PYTHON"
else
  PYTHON_BIN="$(command -v python3.11 || command -v python)"
fi
echo "[vibe-hpc-smoke] python=$PYTHON_BIN"
"$PYTHON_BIN" --version
"$PYTHON_BIN" - <<'"'"'PY'"'"'
import importlib
import sys

checks = [
    ("minisweagent", "1.17.5"),
    ("swebench", None),
    ("yaml", None),
    ("docker", None),
]
for name, expected in checks:
    module = importlib.import_module(name)
    version = getattr(module, "__version__", "unknown")
    print(f"[vibe-hpc-smoke] import {name}: {version}")
    if expected is not None and version != expected:
        raise SystemExit(f"{name} version mismatch: expected {expected}, got {version}")
print(f"[vibe-hpc-smoke] sys.executable={sys.executable}")
PY

if [[ "0" == "1" ]]; then
  test -n "${DEEPSEEK_API_KEY:-}" || {
    echo "DEEPSEEK_API_KEY is required but not present in the HPC job environment" >&2
    exit 20
  }
  echo "[vibe-hpc-smoke] DEEPSEEK_API_KEY is present"
else
  if [[ -n "${DEEPSEEK_API_KEY:-}" ]]; then
    echo "[vibe-hpc-smoke] DEEPSEEK_API_KEY is present"
  else
    echo "[vibe-hpc-smoke] DEEPSEEK_API_KEY is not set; API-dependent jobs will need it"
  fi
fi

command -v docker
docker --version
docker info >/tmp/vibe_hpc_docker_info.txt
sed -n '"'"'1,40p'"'"' /tmp/vibe_hpc_docker_info.txt
docker image ls --format '"'"'{{.Repository}}:{{.Tag}}\t{{.Size}}'"'"' | sed -n '"'"'1,20p'"'"'

"$PYTHON_BIN" -m src.environment.docker_env maintain   --max-cached-images "4"   --max-concurrent 1   --min-free-gb "5"

echo "[vibe-hpc-smoke] completed at $(date)"'
exit_code=$?
set -e
echo "[ulhpc-submit] exit_code=$exit_code"
echo "[ulhpc-submit] job finished at $(date)"
exit $exit_code
