#!/bin/bash -l
# This script was generated by ulhpc-submit
# Generated at: 2026-06-21T18:19:54

#SBATCH --job-name=gepa-ref-smoke-apptainer
#SBATCH --partition=batch
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G
#SBATCH --time=02:00:00
#SBATCH --output=job_%j.out
#SBATCH --error=job_%j.err
#SBATCH --chdir=/home/users/twang/hpc_runs/vibe-coding-planning

set -uo pipefail
echo "[ulhpc-submit] job started at $(date)"
echo "[ulhpc-submit] running on host: $(hostname)"
echo "[ulhpc-submit] remote dir: /home/users/twang/hpc_runs/vibe-coding-planning"

echo "[ulhpc-submit] configuring environment on compute node"
if module load miniconda3 2>/dev/null && command -v conda >/dev/null 2>&1; then
    echo "[ulhpc-submit] using conda environment"
    set +u  # avoid conda uninitialized-variable errors
    source "$(conda info --base)/etc/profile.d/conda.sh"
    set -u
    if ! conda env list | grep -qE "^\s*mini-swe\s+"; then
        conda create -n mini-swe python=3.11 -y
    else
        conda run -n mini-swe pip install -r requirements.txt
    fi
    conda activate mini-swe
    pip install -r requirements.txt
else
    echo "[ulhpc-submit] WARNING: conda not available; falling back to pip. Some packages may differ from the conda environment."
    module load lang/Python/3.11
    python -m pip install --user -r requirements.txt
fi
echo "[ulhpc-submit] environment ready"

echo "[ulhpc-submit] executing user command"
set +e
bash -lc 'source /etc/profile.d/modules.sh && module load lang/Python/3.11 tools/Apptainer && export DEEPSEEK_API_KEY='"'"'sk-0185460626d848a6b27cf88031c728a9'"'"' && python3 scripts/internal/run_gepa_rules.py --config configs/gepa_verified_rules_reflection_smoke_apptainer.yaml'
exit_code=$?
set -e
echo "[ulhpc-submit] exit_code=$exit_code"
echo "[ulhpc-submit] job finished at $(date)"
exit $exit_code
