"""Contrastive analysis agent.

Runs on the host machine using DefaultAgent + LocalEnvironment.
The agent receives file paths only and reads files itself via shell commands.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from src.agents._deps import build_default_agent, build_model, import_minisweagent
from src.analysis.case_loader import CaseDescriptor
from src.config import Config
from src.exceptions import TaskError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Prompt templates (CONTRAPROMPT-style)
# ---------------------------------------------------------------------------

CONTRASTIVE_SYSTEM_TEMPLATE = """\
You are a contrastive reasoning analyst. Your task is to compare a FAILED plan with a SUCCESSFUL plan for the same software-engineering bug-fix task, understand what made the difference, and extract generalizable rules.

You will be given a list of file paths. Read them yourself. YOU decide which files to read and in what order — do not read everything at once.

Your core question: "What did the improved reasoning do differently in its chain of thought?"

For each distinct reasoning difference you identify, extract one rule in this EXACT format:

When [input pattern], [strategy] because [causal justification].

Requirements for each rule:
- [input pattern]: describes a recognizable flaw, situation, or warning sign in a plan's reasoning
- [strategy]: describes what better reasoning or planning should do instead
- [causal justification]: explains the underlying mechanism WHY the strategy works
- The rule must be generalizable beyond this specific task — no specific filenames, function names, or line numbers
- Focus on reasoning patterns and cognitive strategies, not implementation details

You may extract multiple rules if you find multiple distinct reasoning differences. Each rule should capture one independent pattern.

After extracting all rules, you MUST write them to {{RULE_FILE_PATH}} using a simple shell command (e.g. printf or echo with > redirection). Do NOT use heredoc (<< EOF). Do NOT output the rules in your response text — write them to the file only. Then finish with:
echo COMPLETE_TASK_AND_SUBMIT_FINAL_OUTPUT && cat {{RULE_FILE_PATH}}
"""

CONTRASTIVE_INSTANCE_TEMPLATE = """\
Task instance: {{instance_id}}

Data files available at {{data_base_dir}}/{{instance_id}}/:
{{file_list}}

Round summary (for reference):
{{round_summary}}

Instructions:
- Each round contains a plan, its execution trajectory, and the generated patch
- Round 1 is always generated by the plan_agent; rounds >= 2 are generated by the reflect_agent
- Read the files you need, identify which round(s) failed and which succeeded, compare their reasoning chains, and extract rules.
"""


# ---------------------------------------------------------------------------
# Helper: build instance prompt text
# ---------------------------------------------------------------------------

def _build_file_list(case: CaseDescriptor) -> str:
    """Build a human-readable file list for the instance prompt."""
    lines: list[str] = []
    for rd in case.rounds:
        lines.append(f"Round {rd.round_num}:")
        lines.append(f"  - {rd.plan_path}")
        lines.append(f"  - {rd.plan_trajectory_path}")
        if rd.code_trajectory_path:
            lines.append(f"  - {rd.code_trajectory_path}")
        lines.append(f"  - {rd.patch_path}")
    lines.append("Shared:")
    lines.append("  - result.json (contains resolved status and test results for all rounds)")
    return "\n".join(lines)


def _build_round_summary(case: CaseDescriptor) -> str:
    """Build a short round summary showing resolved status per round."""
    parts: list[str] = []
    for rd in case.rounds:
        status = "resolved" if rd.resolved else "failed"
        parts.append(f"  Round {rd.round_num}: {status} (generated_by={rd.generated_by})")
    return "\n".join(parts)


def _read_rule_from_file(env: Any, rule_path: str) -> str | None:
    """Try to read the rule file from the local environment."""
    try:
        result = env.execute(f"cat {rule_path}")
        if result.get("returncode") == 0:
            content = result.get("output", "").strip()
            if content:
                return content
    except Exception:
        pass
    return None


def _extract_rule_from_messages(messages: list[dict[str, Any]]) -> str | None:
    """Fallback: extract rule from assistant messages containing rule content.

    Scans all assistant messages (newest first) and returns the first one
    that contains at least one line starting with 'When ' and containing
    ' because '.  This avoids capturing submit commands or heredoc
    attempts when the rule file was not written correctly.
    """
    for msg in reversed(messages):
        if msg.get("role") != "assistant":
            continue
        content = msg.get("content", "")
        if not content:
            continue
        # Look inside ```-fenced blocks first
        if "```" in content:
            parts = content.split("```")
            for block in parts[1::2]:  # Every odd index is inside a fence
                block = block.strip()
                # Strip language identifier line if present
                lines = block.split("\n", 1)
                candidate = lines[1] if len(lines) == 2 else block
                if _looks_like_rule(candidate):
                    return candidate.strip()
        # Then check the raw content
        if _looks_like_rule(content):
            return content.strip()
    return None


def _looks_like_rule(text: str) -> bool:
    """Return True if text contains at least one plausible rule line."""
    for line in text.splitlines():
        line = line.strip()
        if line.lower().startswith("when ") and " because " in line.lower():
            return True
    return False


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def run(
    config: Config,
    case: CaseDescriptor,
    data_base_dir: str,
) -> tuple[str, list[dict[str, Any]]]:
    """Run the contrastive analysis agent for a single case.

    Args:
        config: Full configuration object (uses config.analysis for model settings).
        case: CaseDescriptor with per-round file paths.
        data_base_dir: Absolute path to the reflect_success_cases directory.

    Returns:
        A tuple of (rule_text, trajectory_messages).

    Raises:
        TaskError: If the agent produces empty or invalid output.
    """
    DefaultAgent, LitellmModel, _ = import_minisweagent()
    from minisweagent.environments.local import LocalEnvironment

    analysis_cfg = config.analysis

    # Use an instance-isolated temp file so stale rules from prior cases are never reused.
    rule_path = f"/tmp/rule_{case.instance_id}.md"

    # Build model using analysis-specific API key and base
    model = build_model(
        LitellmModel,
        model_name=analysis_cfg.model,
        api_key=config.analysis_api_key,
        api_base=analysis_cfg.api_base,
    )

    # LocalEnvironment: agent runs shell commands directly on the host
    # Set cwd to data_base_dir so relative paths in the prompt resolve correctly
    env = LocalEnvironment(cwd=str(data_base_dir))

    # Clean up any stale rule file before starting this case
    try:
        env.execute(f"rm -f {rule_path}")
    except Exception:
        pass

    # Inject the instance-specific file path into the system prompt
    system_template = CONTRASTIVE_SYSTEM_TEMPLATE.replace("{{RULE_FILE_PATH}}", rule_path)

    agent = build_default_agent(
        DefaultAgent,
        model=model,
        environment=env,
        system_template=system_template,
        step_limit=analysis_cfg.max_steps,
        cost_limit=analysis_cfg.cost_limit,
        instance_template=CONTRASTIVE_INSTANCE_TEMPLATE,
    )

    logger.info(
        "Starting contrastive analysis for %s: model=%s step_limit=%s rule_path=%s",
        case.instance_id,
        analysis_cfg.model,
        analysis_cfg.max_steps,
        rule_path,
    )

    # Prepare instance prompt variables
    file_list = _build_file_list(case)
    round_summary = _build_round_summary(case)

    exception_name, exception_msg = agent.run(
        task=case.instance_id,
        instance_id=case.instance_id,
        data_base_dir=data_base_dir,
        file_list=file_list,
        round_summary=round_summary,
    )

    # Try to read rule from the file the agent wrote
    rule_text = _read_rule_from_file(env, rule_path)
    if rule_text is None:
        if exception_name == "Submitted":
            # Agent claimed submission but file is empty — try to salvage from messages
            rule_text = _extract_rule_from_messages(agent.messages)
            if rule_text is None:
                raise TaskError(
                    f"Contrastive agent for {case.instance_id} submitted but no rule "
                    f"found in messages or {rule_path}."
                )
            logger.warning(
                "[%s] Rule file empty but found rule content in messages; "
                "consider tightening the prompt",
                case.instance_id,
            )
        else:
            raise TaskError(
                f"Contrastive agent for {case.instance_id} terminated without submission "
                f"(exit_status={exception_name}). Expected the agent to write a rule to {rule_path}."
            )

    if not rule_text or not rule_text.strip():
        raise TaskError(
            f"Contrastive agent for {case.instance_id} submitted but {rule_path} was empty."
        )

    rule_text = rule_text.strip()
    if len(rule_text) < 30:
        raise TaskError(
            f"Contrastive agent output too short ({len(rule_text)} chars) for {case.instance_id}. "
            "Expected a meaningful rule."
        )

    return rule_text, agent.messages
